# ---- deps ----
FROM node:20-alpine AS deps
WORKDIR /app

COPY package*.json ./
RUN npm ci


# ---- build ----
FROM node:20-alpine AS build
WORKDIR /app

ARG NEXT_PUBLIC_HUBSPOT_PORTAL_ID
ARG NEXT_PUBLIC_HUBSPOT_FORM_GUID

ENV NEXT_PUBLIC_HUBSPOT_PORTAL_ID=$NEXT_PUBLIC_HUBSPOT_PORTAL_ID
ENV NEXT_PUBLIC_HUBSPOT_FORM_GUID=$NEXT_PUBLIC_HUBSPOT_FORM_GUID
ENV NEXT_PUBLIC_META_PIXEL_ID=$NEXT_PUBLIC_META_PIXEL_ID

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN npm run build


# ---- run ----
FROM node:20-alpine AS run
WORKDIR /app

ENV NODE_ENV=production

COPY --from=build /app/package*.json ./
COPY --from=build /app/next.config.* ./
COPY --from=build /app/public ./public
COPY --from=build /app/.next ./.next
COPY --from=build /app/node_modules ./node_modules

EXPOSE 3001

CMD ["npm", "run", "start", "--", "-p", "3001"]