export const EGYPT_CITIES = [
  { key: "cairo", label: "القاهرة" },
  { key: "giza", label: "الجيزة" },
  { key: "alexandria", label: "الإسكندرية" },
  { key: "dakahlia", label: "الدقهلية" },
  { key: "red_sea", label: "البحر الأحمر" },
  { key: "beheira", label: "البحيرة" },
  { key: "fayoum", label: "الفيوم" },
  { key: "gharbia", label: "الغربية" },
  { key: "ismailia", label: "الإسماعيلية" },
  { key: "monufia", label: "المنوفية" },
  { key: "minya", label: "المنيا" },
  { key: "qalyubia", label: "القليوبية" },
  { key: "new_valley", label: "الوادي الجديد" },
  { key: "suez", label: "السويس" },
  { key: "aswan", label: "أسوان" },
  { key: "assiut", label: "أسيوط" },
  { key: "beni_suef", label: "بني سويف" },
  { key: "port_said", label: "بورسعيد" },
  { key: "damietta", label: "دمياط" },
  { key: "sharqia", label: "الشرقية" },
  { key: "south_sinai", label: "جنوب سيناء" },
  { key: "kafr_el_sheikh", label: "كفر الشيخ" },
  { key: "matrouh", label: "مطروح" },
  { key: "luxor", label: "الأقصر" },
  { key: "qena", label: "قنا" },
  { key: "north_sinai", label: "شمال سيناء" },
  { key: "sohag", label: "سوهاج" },
] as const;

export type EgyptCityKey = (typeof EGYPT_CITIES)[number]["key"];
